### ISSUE TITLE
Importing a csv to taiga

### ISSUE THREAD

**Issue by datatalking** [richbl/taiga.io-scripts#2]
So I'm not a complete newby but there is NOT a csv import for this in the GUI... is there some kind of 'host this product' and learn 14 lines of code to get a simple CSV loaded of the projects we want to use for Taiga?

**Comment by richbl** [comment]
@datatalking, I'm not sure what your question is. What would you want to import into Taiga using CSV? This project does offer a bulk import script that uses a tab-delimited file format (no CSV) to add stories to a Taiga project.

As for your "host this product" idea, you might want to contact the folks at [Taiga.io](https://taiga.io/) directly. I do know that you can create public projects with a free account. They also provide [an excellent and very complete Taiga API that you can study](https://taigaio.github.io/taiga-doc/dist/api.html): I've used it extensively for this and other Taiga-based projects.

**Comment by datatalking** [comment]
Yes I wanted to import a csv or a tsv file would be file. Do I have to code this or is it an actual prebuilt function?

**Comment by richbl** [comment]
In `taiga_import_story.sh`, see the logic around line 116 (comment `Parse tab-delimited ARG_INPUTFILE and POST stories`). Between here and line 154, the script loops through the lines in the input file, parsing each line and then posting each story via the Taiga.io API call for posting user stories (`/api/v1/userstories`). Note that the current logic is delimiting with a tab character (`while IFS=$'\t'`), so if you really want to parse for CSV, it should be as simple as dropping the tab delimiter, and replacing it with a comma (e.g., `IFS=,`).
