### ISSUE TITLE
Project Slug

### ISSUE THREAD

**Issue by mudit94** [richbl/taiga.io-scripts#3]
What is meant by project slug name? How do I obtain it?

**Comment by richbl** [comment]
The project slug is used by Taiga internally as a reference identifier. I'd recommend that you refer to the [Taiga API documentation](https://taigaio.github.io/taiga-doc/dist/api.html). [Here's some specific documentation references to project slugs](https://taigaio.github.io/taiga-doc/dist/api.html#projects-get-by-slug).
