### ISSUE TITLE
issue with tags

### ISSUE THREAD

**Issue by langdon** [richbl/taiga.io-scripts#4]
I tried running your import script with 2 tags. Taiga gave me errors about the empty tag. I presume something changed in the API for import. Just fyi, I just hacked the script cause I only ever needed 2.

**Comment by richbl** [comment]
@langdon, you're probably right. I haven't used this script since I wrote it ~2015, so I'm sure the Taiga API has changed (perhaps significantly). If you have something that works, create a pull request and we'll get it updated in the code base. Thanks

**Comment by langdon** [comment]
I would but.. I just deleted the 3rd tag... cause writing a sophisticated loop was beyond the time I could spend on it :/ . For now, for anyone who finds this, workaround is just to delete the:
```
                            "'"${FILE_TAG1}"'",
                            "'"${FILE_TAG2}"'",
                            "'"${FILE_TAG3}"'"
```

that you don't need. However, be careful of the pesky json commas, The error from the API is not very obvious when you make this mistake:
```
                            "'"${FILE_TAG1}"'",
                            "'"${FILE_TAG2}"'",
```

**Comment by richbl** [comment]
Thanks @langdon. I'll add a note in the README file to indicate that this application is out of sync with the latest Taiga API (located here: https://docs.taiga.io/#api).
